### ISSUE TITLE
Параметры задаются при вызове программы, а не запрашиваются в диалоге

### ISSUE THREAD

**Issue by ds-zelax** [EfraimV/Stadzirovka#1]
https://github.com/EfraimTzimisce/Stadzirovka/blob/75555d4cd61a62a10c1a80db7d622aa41ad088e8/Main#L24C4-L24C5 - параметры должны задачать ся при вызове, т.е. в командной строке - "Программа - консольное приложение, в качестве параметров при вызове принимает одно или два целых числа..."

**Comment by EfraimV** [comment]
Убрал запрос input от пользователя в коде программы.

**Comment by ds-zelax** [comment]
+
