### ISSUE TITLE
Первая часть - однопоточный вариант

### ISSUE THREAD

**Issue by ds-zelax** [EfraimV/Stadzirovka#2]
https://github.com/EfraimTzimisce/Stadzirovka/blob/75555d4cd61a62a10c1a80db7d622aa41ad088e8/Main#L41
Для начала предлагаю решить первую часть задачи. Для второй код придется модифицировать. Поэтому пока прошу потоки убрать.

**Comment by EfraimV** [comment]
Убрал многопоточность.
