### ISSUE TITLE
Стартовый коммент.

### ISSUE THREAD

**Issue by ds-zelax** [EfraimV/Stadzirovka#3]
https://github.com/EfraimTzimisce/Stadzirovka/blob/75555d4cd61a62a10c1a80db7d622aa41ad088e8/Main#L1
Предлагаю в начале добавить комментарий, в котором указать командную строку (строки) для сборки программы. 
И один-два примера выполнения с распечаткой результата - времени поиска. 
В расчет времени не включать вывод самих чисел.
Сам вывод чисел сделать отключаемым.
Пример такого коммента от одного из предыдущих участников - 
/* строчки для компилятора
g++ -Wall test.cpp -o test

Время работы программы
v1
./test 622337203 ~ 18876 мс
v2
./test 622337203 ~ 18530 мс
v3
./test 622337203 ~ 18224 мс
v4
./test 622337203 ~ 11284 мс
*/

**Comment by EfraimV** [comment]
Спасибо за отзыв! Я сегодня займусь правками и к завтрашнему код отредактирую. Если не успею, то я об этом тут тогда сообщу.

**Comment by EfraimV** [comment]
Добавил время выполнения программы, 3 теста. Добавил комманду для вызова и команду для сборки программы.

**Comment by ds-zelax** [comment]
А не пробовал с тем же параметром, что и в примере?
Или хотя бы раз в 100 меньшим.
Советую попробовать и проанализировать результат.
В примере числа в диапазоне от 1 до 622337203 находятся за 10-20 секунд используя разные модификации алгоритма поиска..

**Comment by EfraimV** [comment]
Попробовал сделать дополнительные тесты. Результат добавлен в комментарии к программе.

**Comment by ds-zelax** [comment]
А не кажется странным результат, что миллионы чисел вычисляются быстрее тысячи?
И косяк с командой сборки - https://github.com/EfraimTzimisce/Stadzirovka/issues/4

**Comment by EfraimV** [comment]
мне показалось странным, я несколько раз программу прогнал, но пока все тоже, сегодня еще надо порыться в интернете, поищу, что может быть причиной

еще, возможно код переписать придется

**Comment by EfraimV** [comment]
Изменил код, добавил дополнительные алгоритмы, указал результаты 3 тестов.

**Comment by ds-zelax** [comment]
Предлагаю убрать неэффективные алгоритмы и из кода и из комментария. Теперь будем пытаться ускорить "решето".

**Comment by ds-zelax** [comment]
Результаты замеров предлагаю накапливать в этом комментарии для наглядности, т.е. после внесения изменений в алгоритм добавлять в комментарий краткое описание этих изменений и результаты замеров с теми же параметрами.

**Comment by EfraimV** [comment]
Убрал из кода алгоритм перебора и алгоритм ферма. Изменил в Эратосфене bool на int, результат приложил.

**Comment by ds-zelax** [comment]
А команда сборки так и не работает, т.к. в команде файл с расширением cpp, а в репозитории - без расширения. 
_**Это уже дважды невнимательность на одном и том же месте!**_

**Comment by EfraimV** [comment]
Доработаю команду, отпишу по результатам.

**Comment by EfraimV** [comment]
Команда, которая в комментарии рабочая, но такой момент. При clone скачивается программа без cpp формата, в этом проблема. Я изменил название файла, так что теперь он корректно скачивает в cpp и собирается.

**Comment by ds-zelax** [comment]
> Команда, которая в комментарии рабочая, но такой момент. При clone скачивается программа без cpp формата, в этом проблема. Я изменил название файла, так что теперь он корректно скачивает в cpp и собирается.
Нет такого термина "cpp формат" ни в русском, ни в английском.
Имя файла в репозитории было без расширения - это и была причина. Иэто говорит о том, что Автор с репозиторием работает как-то странно, не так как положено, т.е. возникает подозрение, что с репозиториями git автор не дружит.

**Comment by ds-zelax** [comment]
Проблемы исправлены - issue закрываю.
