### ISSUE TITLE
Сборка не проходит

### ISSUE THREAD

**Issue by ds-zelax** [EfraimV/Stadzirovka#4]
https://github.com/EfraimTzimisce/Stadzirovka/blob/9aabd91721f81b8381bde68100d54e35e3e0f1a2/Main#L13

Да и не должна, т.к файл в репозитории имеет другое имя.

**Comment by EfraimV** [comment]
сегодня погоняю еще программу, обновлю тогда по результатам, если не получится, опишу, что делал и что не получается
