### ISSUE TITLE
Провести серии замеров с неизменными параметрами и объяснить тут, почему результаты различаются.

### ISSUE THREAD

**Issue by ds-zelax** [EfraimV/Stadzirovka#5]

**Comment by EfraimV** [comment]
Замер времени провел, результат и объяснение в issue 6.

**Comment by EfraimV** [comment]
Провел несколько замеров с одними и теми же параметрами, результат отличается, хотя и не очень сильно.

Это может происходить по нескольким причинам. Во-первых, алгоритм решета Эратосфена основан на принципе исключения чисел, которые являются составными, и этот процесс может происходить в разном порядке в зависимости от того, как числа распределены в памяти компьютера. Таким образом, небольшие различия в порядке исключения чисел могут привести к тому, что некоторые числа будут исключены раньше или позже, что повлияет на конечный результат.
То есть C++ обращается конкретно к тем местам в памяти компьютера, которые содержат искомые данные, и они могут меняться, от этого и может быть разное время поиска - быстрее или медленее.

Во-вторых, алгоритм решета Эратосфена является итеративным, и небольшие различия в скорости выполнения каждой итерации могут накапливаться и приводить к небольшим различиям в конечном результате. У нас итераций много, так что есть чему накопиться.

Также на работу компьютера на языке C++ влияет состояние самого компьютера - не перегревается ли, к примеру. В моем случае он начал работать еще не очень теплым, а поработал - немного нагрелся, это повлияло на результат.

**Comment by ds-zelax** [comment]
> ... Во-первых, алгоритм решета Эратосфена основан на принципе исключения чисел, которые являются составными, и этот процесс может происходить в разном порядке в зависимости от того, как числа распределены в памяти компьютера...

Прошу это пояснить, можно для начала на примерах. Каким образом на разных запусках одного и того же кода могут получаться "разчичные расположения в памяти" одних и тех же денных? 

> ... Таким образом, небольшие различия в порядке исключения чисел могут привести к тому, что некоторые числа будут исключены раньше или позже, что повлияет на конечный результат...

Это тоже прошу пояснить. Каким образом ни одних и тех же исходных данных у одного и того же алгоритма (кода) может быть разный "порядок исключения чисел"?

>... Также на работу компьютера на языке C++ влияет состояние самого компьютера - не перегревается ли, к примеру. В моем случае он начал работать еще не очень теплым, а поработал - немного нагрелся, это повлияло на результат.

Тогда результат будет стабильно ухудшаться или улучшаться. Прошу проверить эту гипотезу экспериментально.

Еще идеи есть?

**Comment by EfraimV** [comment]
Еще изучу вопрос тогда, посижу поосновательнее, в среду будет результат.

**Comment by EfraimV** [comment]
"Прошу это пояснить, можно для начала на примерах. Каким образом на разных запусках одного и того же кода могут получаться "различные расположения в памяти" одних и тех же данных?"

Операционные системы используют различные стратегии управления памятью. Например, при каждом запуске программы операционная система может выделять память в разных местах, что может привести к тому, что массивы и другие структуры данных будут находиться по разным адресам в памяти.
Компиляторы могут оптимизировать код различными способами, что может повлиять на порядок выполнения операций и расположение данных в памяти. Например, компилятор может решить изменить порядок переменных или использовать разные стратегии для хранения данных.
Кэш-память процессора может влиять на то, как быстро данные загружаются в память и как они располагаются. Это может также привести к различиям в производительности между запусками.

**Comment by EfraimV** [comment]
"Каким образом ни одних и тех же исходных данных у одного и того же алгоритма (кода) может быть разный "порядок исключения чисел"?"

Возможно, я не совсем правильно выразился, речь все еще идет о том, что процессор в ходе выполнения программы обращается к разным участкам памяти, откуда он образно выражаясь, берет данные. Так что у нас будут исключены решетом одни и теже числа, и порядок тоже будет одинаковым при каждом запуске программы, но из за того, где в памяти находится информация о них, из за этого и будет разница.

**Comment by EfraimV** [comment]
Для экспериментальной проверки того, как именно влияет температура процессора на скорость поиска простых чисел, понадобится чуть больше времени, и надо будет еще кое какие утилиты поставить, чтобы "понагружать" его немного. Сделаю это чуть позже.

**Comment by ds-zelax** [comment]
Стоит почитать про механизмы управления памятью в ОС, поскольку то, что написано выше весьма безграмотно. Тут пробел. Из-за того, что под задачу ОС выделяет разные страницы физической памяти время выполнения зависеть не может, т.к. быстродействие всей оперативной памяти одинаковое, точнее ОС устанавливает временнЫе характеристики работы с памятью, ориентируясь на самый медленный из модулей установленных в системе, либо просто отказывается работать с модулями с разными характеристиками.
Предлагаю продолжить поиски причины различных результатов замеров быстродействия. Подсказка - почитать про команду ps.

**Comment by EfraimV** [comment]
При вводе команды я вижу процессы, которые сейчас запущены (еще поигрался с вариациями ps aux, ps -e и top (это отдельная команда)), вижу процессы, которые сейчас запущены.
Таким образом можно сделать вывод, что время работы программы может также меняться из за того, что процессы требуют ресурсы процессора, и программа конкурирует с ними.

К примеру, я запускал программу - один и тот же код на своей виртуальной машине на десктопе, и на ноутбуке, где у меня только линукс стоит. На линуксе получалось 14834-15873 миллисекунд, а вот на виртуальной машине 94761-97681 миллисекунд.  
То есть на компьютере, где запущена виртуальная машина больше процессов, и таким образом, они замедляют работу программы. 
Scheduler распределяет ресурсы процессора на выполнение программ. Это может меняться от одного запуска программы к другому, например, потому как к примеру определенные daemon'ы, которые активируются и выключаются в процессе функционирования ядра операционной системы, и они тоже требуют ресурсы процессора.
Ну, а на десктопе, где виртуальная машина, там полный набор - и линукс процессы, и виндоуз, все это требует ресуры.

Таким образом, наличие других процессов в системе - даже процессов, которые связаны с функционированием системы уже влияют на время выполнения программы.

**Comment by ds-zelax** [comment]
Да. Именно влияние других процессов в ОС даёт разницу в результатах замеров времени.
